#!/usr/bin/env python3
"""Analyze AI API Tester JSON reports and classify failures."""

import argparse
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from ai_api_tester.failure_analyzer import analyze_report


def main():
    parser = argparse.ArgumentParser(description="Analyze failed API test report")
    parser.add_argument("report", help="JSON report generated by run_tests.py")
    parser.add_argument("--context-json", default=None, help="Optional context JSON generated by gen_context.py")
    parser.add_argument("--output", "-o", default=None, help="Optional JSON output path")
    args = parser.parse_args()

    report_path = Path(args.report)
    if not report_path.exists():
        print(f"File not found: {report_path}")
        sys.exit(1)

    report = json.loads(report_path.read_text(encoding="utf-8"))
    context = {}
    if args.context_json:
        context_path = Path(args.context_json)
        if not context_path.exists():
            print(f"Context file not found: {context_path}")
            sys.exit(1)
        context = json.loads(context_path.read_text(encoding="utf-8"))

    analysis = analyze_report(report, context=context)

    print(f"失败分析: {analysis['api']}")
    print(f"汇总: {analysis['summary_zh']}")
    for finding in analysis["findings"]:
        print("")
        print(f"{finding['id']}: {finding['name']}")
        print(f"  类型: {finding['classification_zh']} ({finding['classification']})")
        print(f"  严重度: {finding['severity']}")
        if finding.get("source"):
            print(f"  来源: {finding['source']}")
        if finding.get("response_status"):
            print(f"  HTTP: {finding['response_status']}")
        print(f"  原因: {finding['reason_zh']}")
        print(f"  建议: {finding['suggestion_zh']}")
        source_context = finding.get("source_context")
        if source_context:
            print(f"  代码: {source_context['file']}:{source_context['line']}")

    if args.output:
        output_path = Path(args.output)
        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text(json.dumps(analysis, ensure_ascii=False, indent=2), encoding="utf-8")
        print(f"\nAnalysis saved: {output_path}")

    sys.exit(1 if analysis["findings"] else 0)


if __name__ == "__main__":
    main()
